### PR TITLE
Remove job name length limit

### PR DESCRIPTION
**Pull request by Kobzol**
Fixes: https://github.com/It4innovations/hyperqueue/issues/482

### CODE REVIEW

**Review by spirali — CHANGES_REQUESTED** [review]
Please put some truncate in table in ``hq job list``

**Review by spirali — APPROVED** [review]
Good job! (I would be more strict in the main output list then 70 chars (e.g. 30?), but we can always change this :)

**Comment by Kobzol** [comment]
I have shortened it to 50 characters.

**Comment by spirali** [comment]
> I have shortened it to 50 characters.

:+1: 

(btw: Do not forget to update CHANGELOG:)

**Pull request merged**
